Repository AgusGomezDAddario/proyecto-cristales, pull requests merged in 2025-09, with the labels that each got.

#1 LES GUSTA UN PR DE BUENAS PRÁCTICAS PARA LAS MIGRACIONES?
  database/migrations/2025_09_17_214621_crear_estructura_basica.php
  database/seeders/DatabaseSeeder.php
  database/seeders/DatosInicialesSeeder.php
Labels: enhancement

#2 Backend para los movimientos de ingresos y egresos
  app/Http/Controllers/ConceptoController.php
  app/Http/Controllers/MovimientoController.php
  app/Models/Concepto.php
  app/Models/MedioDePago.php
  app/Models/Movimiento.php
  database/migrations/2025_09_21_170041_crear_tabla_movimientos.php
  routes/web.php
Labels: enhancement

#4 Implementación de CRUD para Órdenes de Trabajo
  .env.example
  app/Http/Controllers/OrdenDeTrabajoController.php
  app/Models/DetalleOrdenDeTrabajo.php
  app/Models/Estado.php
  app/Models/MedioDePago.php
  app/Models/OrdenDeTrabajo.php
  app/Models/Precio.php
  app/Models/Titular.php
  app/Models/Vehiculo.php
  database/factories/DetalleOrdenDeTrabajoFactory.php
  database/factories/OrdenDeTrabajoFactory.php
  database/factories/PrecioFactory.php
  database/factories/TitularFactory.php
  database/factories/VehiculoFactory.php
  database/seeders/SeederDatosDePrueba.php
  package-lock.json
  package.json
  resources/css/app.css
  resources/css/theme.css
  resources/js/app.tsx
  resources/js/components/appearance-dropdown.tsx
  resources/js/components/ui/button.tsx
  resources/js/components/ui/input.tsx
  resources/js/pages/ordenes/create.tsx
  resources/js/pages/ordenes/createOrdenes.tsx
  resources/js/pages/ordenes/edit.tsx
  resources/js/pages/ordenes/index.tsx
  resources/js/pages/ordenes/show.tsx
  routes/web.php
Labels: enhancement

#5 Feature/login
  app/Http/Controllers/Administrador/userController.php
  app/Http/Controllers/Auth/AuthenticatedSessionController.php
  app/Http/Middleware/isAdmin.php
  app/Http/Requests/Auth/LoginRequest.php
  app/Models/Role.php
  app/Models/User.php
  bootstrap/app.php
  composer.json
  composer.lock
  database/migrations/2025_09_29_000000_create_rol_table.php
  database/migrations/2025_09_29_000001_create_users_table.php
  database/seeders/DatosInicialesSeeder.php
  package-lock.json
  resources/js/components/user-info.tsx
  resources/js/components/user-menu-content.tsx
  resources/js/pages/Administrador/Dashboard.tsx
  resources/js/pages/Administrador/usuarios.tsx
  resources/js/pages/Empleado/Dashboard.tsx
  resources/js/pages/auth/login.tsx
  resources/lang/es/auth.php
  resources/lang/es/validation.php
  routes/web.php
Labels: good first issue

#6 Cambios en archivo de rutas
  routes/web.php
Labels: bug
